version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      - SECRET_KEY=samplesecret123
      - DEBUG=0
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx_config
    ports:
      - "8080:8080"
    depends_on:
      - app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
